# Generated by Django 2.1.1 on 2018-09-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedReview',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommender.Review')),
            ],
            options={
                'db_table': 'analyzed_reviews',
            },
        ),
    ]
