# Generated by Django 2.1.1 on 2018-09-23 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_analyzedreview_jumanpp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzedreview',
            old_name='jumanpp',
            new_name='jumanpp_content',
        ),
        migrations.RenameField(
            model_name='analyzedreview',
            old_name='mecab_neologd',
            new_name='neologd_content',
        ),
        migrations.AddField(
            model_name='analyzedreview',
            name='jumanpp_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=255), blank=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='analyzedreview',
            name='neologd_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=255), blank=True, size=None), blank=True, null=True, size=None),
        ),
    ]
