version: '3'
services:
  batch:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app:cached
      - ./static/:/app/static:cached
    command: python3 manage.py runserver 0.0.0.0:8000
    deploy:
      resources:
        limits:
          memory: 11G
        reservations:
          memory: 10G
    expose:
      - 8000
    env_file:
       - ./.env
    depends_on:
      - db
  db:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.09"
    command:
      ["/cloud_sql_proxy",
      "-instances=${INSTANCE_NAME}=tcp:0.0.0.0:5432"]
    ports:
      - "5432:5432"
