version: '2'
services:
  batch:
    mem_limit: 8gb
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app:cached
      - ./static/:/app/static:cached
    command: ["runserver", "0.0.0.0:8000"]
    expose:
      - 8000
    env_file:
       - ./.env
    depends_on:
      - db
      - juman-api
    networks:
      - gr_network
  juman-api-back-end:
    image: gkmr/jumanpp-api
    networks:
      - gr_network
    ports:
      - '4567'
  juman-api:
    image: "dockercloud/haproxy:latest"
    links:
      - juman-api-back-end
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gr_network
  db:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.09"
    command:
      ["/cloud_sql_proxy",
      "-instances=${INSTANCE_NAME}=tcp:0.0.0.0:5432"]
    ports:
      - "5432:5432"
    networks:
      - gr_network
networks:
  gr_network:
