version: '3'
services:
  batch:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app:cached
      - ./static/:/app/static:cached
    command: python3 manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file:
       - ./.env
